name: nuxt-blog-laravel

services:
  appserver:
    type: php:8.3
    webroot: public
    via: nginx
    ssl: true
    environment:
      MYSQL_VERSION: "8"
  node:
    type: node:20
    healthcheck: true
  database:
    type: mysql:8.0

tooling:
  install:
    service: appserver
    cmd:
      - composer install --no-cache
      - php -r "file_exists('.env') || copy('.env.example', '.env');"
      - php artisan key:generate
      - php artisan migrate --seed
      - php artisan storage:link
  npm:
    service: node
    cmd:
      - npm install
  tinker:
    service: appserver
    cmd:
      - php artisan tinker
